// import React from "react";
// import useAi from "../hooks/useAI";
// import ReactMarkdown from "react-markdown";
// import remarkGfm from "remark-gfm";

// const AISummary = () => {

//     const {
//         selectedSummary,
//         isSummaryOpen,
//         setIsSummaryOpen,
//     } = useAi();

//     if (!isSummaryOpen || !selectedSummary) {
//         return null;
//     }

//     return (

//         <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex justify-center items-center z-50 p-5 animate-in fade-in duration-200">

//             <div className="bg-white rounded-2xl shadow-2xl w-full max-w-5xl h-[85vh] flex flex-col border border-gray-150 overflow-hidden animate-in zoom-in-95 duration-200">

//                 {/* Header */}

//                 <div className="flex justify-between items-start border-b border-gray-100 p-6 bg-slate-50/50">

//                     <div>

//                         <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2">
//                             📋 Whiteboard AI Summary
//                         </h2>

//                         <p className="text-xs text-gray-500 mt-1">

//                             Generated by:

//                             <span className="font-semibold text-gray-700 ml-1">

//                                 {selectedSummary.createdBy?.fullname || "Unknown"}

//                             </span>

//                             <span className="mx-2 text-gray-300">|</span>

//                             <span>{new Date(selectedSummary.createdAt).toLocaleString()}</span>

//                         </p>

//                     </div>

//                     <button
//                         onClick={() => setIsSummaryOpen(false)}
//                         className="text-gray-400 hover:text-gray-600 transition text-2xl font-bold p-1 cursor-pointer"
//                     >
//                         &times;
//                     </button>

//                 </div>

//                 {/* Body */}

//                 <div className="flex-1 overflow-y-auto p-6 space-y-8">

//                     {/* Snapshot */}

//                     <div>

//                         <h3 className="text-sm font-bold text-gray-800 uppercase tracking-wider mb-3">
//                             📸 Canvas Snapshot
//                         </h3>

//                         <img
//                             src={selectedSummary.imageUrl}
//                             alt="Snapshot"
//                             className="rounded-xl border border-gray-200 shadow-sm w-full bg-slate-50"
//                         />

//                     </div>

//                     {/* Summary */}

//                     <div className="border-t border-gray-100 pt-6">

//                         <h3 className="text-sm font-bold text-gray-800 uppercase tracking-wider mb-4">
//                             📝 AI Summary Documentation
//                         </h3>

//                         <div className="bg-white rounded-xl border border-gray-200/80 p-6 shadow-sm overflow-hidden">
//                             <ReactMarkdown
//                                 remarkPlugins={[remarkGfm]}
//                                 components={{
//                                     h1: ({ ...props }) => <h1 className="text-2xl font-bold text-gray-900 border-b pb-2 mt-6 mb-4 font-sans" {...props} />,
//                                     h2: ({ ...props }) => <h2 className="text-xl font-semibold text-gray-800 border-b pb-1 mt-5 mb-3 font-sans" {...props} />,
//                                     h3: ({ ...props }) => <h3 className="text-lg font-semibold text-gray-800 mt-4 mb-2 font-sans" {...props} />,
//                                     h4: ({ ...props }) => <h4 className="text-base font-semibold text-gray-800 mt-3 mb-2 font-sans" {...props} />,
//                                     h5: ({ ...props }) => <h5 className="text-sm font-semibold text-gray-800 mt-3 mb-2 font-sans" {...props} />,
//                                     h6: ({ ...props }) => <h6 className="text-xs font-semibold text-gray-500 uppercase mt-3 mb-2 font-sans" {...props} />,
//                                     p: ({ ...props }) => <p className="text-gray-700 my-3 leading-relaxed text-sm" {...props} />,
//                                     ul: ({ ...props }) => <ul className="list-disc pl-6 my-3 space-y-1.5 text-gray-700 text-sm" {...props} />,
//                                     ol: ({ ...props }) => <ol className="list-decimal pl-6 my-3 space-y-1.5 text-gray-700 text-sm" {...props} />,
//                                     li: ({ ...props }) => <li className="text-gray-700" {...props} />,
//                                     blockquote: ({ ...props }) => (
//                                         <blockquote className="border-l-4 border-indigo-500 pl-4 italic text-gray-600 my-4 bg-indigo-50/40 py-2 rounded-r" {...props} />
//                                     ),
//                                     hr: ({ ...props }) => <hr className="my-6 border-gray-200" {...props} />,
//                                     strong: ({ ...props }) => <strong className="font-bold text-gray-900" {...props} />,
//                                     em: ({ ...props }) => <em className="italic" {...props} />,
//                                     a: ({ ...props }) => <a className="text-indigo-600 hover:text-indigo-800 underline transition" {...props} />,
//                                     pre: ({ ...props }) => <pre className="bg-gray-900 text-gray-100 rounded-lg p-4 my-4 overflow-x-auto text-xs leading-5 shadow-inner" {...props} />,
//                                     code: ({ className, children, ...props }) => {
//                                         const isBlock = /language-(\w+)/.test(className || "") || String(children).includes("\n");
//                                         return isBlock ? (
//                                             <code className={`${className} block font-mono text-gray-100`} {...props}>
//                                                 {children}
//                                             </code>
//                                         ) : (
//                                             <code className="bg-gray-100 text-indigo-600 px-1.5 py-0.5 rounded text-xs font-mono font-semibold" {...props}>
//                                                 {children}
//                                             </code>
//                                         );
//                                     },
//                                     table: ({ ...props }) => (
//                                         <div className="overflow-x-auto my-6 border border-gray-200 rounded-lg shadow-sm">
//                                             <table className="min-w-full divide-y divide-gray-200 bg-white" {...props} />
//                                         </div>
//                                     ),
//                                     thead: ({ ...props }) => <thead className="bg-gray-50" {...props} />,
//                                     tbody: ({ ...props }) => <tbody className="divide-y divide-gray-200" {...props} />,
//                                     tr: ({ ...props }) => <tr className="hover:bg-gray-50/50 transition" {...props} />,
//                                     th: ({ ...props }) => <th className="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider border-b border-gray-200" {...props} />,
//                                     td: ({ ...props }) => <td className="px-4 py-3 text-sm text-gray-700 border-b border-gray-100" {...props} />,
//                                 }}
//                             >
//                                 {selectedSummary.summary}
//                             </ReactMarkdown>
//                         </div>

//                     </div>

//                 </div>

//                 {/* Footer */}

//                 <div className="border-t border-gray-100 p-4 flex justify-end bg-slate-50/50">

//                     <button
//                         onClick={() => setIsSummaryOpen(false)}
//                         className="bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs px-5 py-2.5 rounded-xl border border-slate-800 shadow transition cursor-pointer"
//                     >
//                         Close
//                     </button>

//                 </div>

//             </div>

//         </div>

//     );
// };

// export default AISummary;


import React from "react";
import useAi from "../hooks/useAI";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const AISummary = () => {

    const {
        selectedSummary,
        isSummaryOpen,
        setIsSummaryOpen,
    } = useAi();

    if (!isSummaryOpen || !selectedSummary) {
        return null;
    }

    return (

        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex justify-center items-center z-50 p-5 animate-in fade-in duration-200">

            <div className="bg-white dark:bg-ink-900 rounded-2xl shadow-2xl w-full max-w-5xl h-[85vh] flex flex-col border border-ink-150 dark:border-ink-700 overflow-hidden animate-in zoom-in-95 duration-200">

                {/* Header */}

                <div className="flex justify-between items-start border-b border-ink-100 dark:border-ink-800 p-6 bg-ink-50/50 dark:bg-ink-800/50">

                    <div>

                        <h2 className="text-xl font-bold text-ink-900 dark:text-white flex items-center gap-2">
                            📋 Whiteboard AI Summary
                        </h2>

                        <p className="text-xs text-ink-500 dark:text-ink-400 mt-1">

                            Generated by:

                            <span className="font-semibold text-ink-700 dark:text-ink-200 ml-1">

                                {selectedSummary.createdBy?.fullname || "Unknown"}

                            </span>

                            <span className="mx-2 text-ink-300 dark:text-ink-600">|</span>

                            <span>{new Date(selectedSummary.createdAt).toLocaleString()}</span>

                        </p>

                    </div>

                    <button
                        onClick={() => setIsSummaryOpen(false)}
                        className="text-ink-400 dark:text-ink-500 hover:text-ink-600 dark:hover:text-ink-300 transition text-2xl font-bold p-1 cursor-pointer"
                    >
                        &times;
                    </button>

                </div>

                {/* Body */}

                <div className="flex-1 overflow-y-auto p-6 space-y-8">

                    {/* Snapshot */}

                    <div>

                        <h3 className="text-sm font-bold text-ink-800 dark:text-ink-100 uppercase tracking-wider mb-3">
                            📸 Canvas Snapshot
                        </h3>

                        <img
                            src={selectedSummary.imageUrl}
                            alt="Snapshot"
                            className="rounded-xl border border-ink-200 dark:border-ink-700 shadow-sm w-full bg-ink-50 dark:bg-ink-800"
                        />

                    </div>

                    {/* Summary */}

                    <div className="border-t border-ink-100 dark:border-ink-800 pt-6">

                        <h3 className="text-sm font-bold text-ink-800 dark:text-ink-100 uppercase tracking-wider mb-4">
                            📝 AI Summary Documentation
                        </h3>

                        <div className="bg-white dark:bg-ink-800 rounded-xl border border-ink-200/80 dark:border-ink-700 p-6 shadow-sm overflow-hidden">
                            <ReactMarkdown
                                remarkPlugins={[remarkGfm]}
                                components={{
                                    h1: ({ ...props }) => <h1 className="text-2xl font-bold text-ink-900 dark:text-white border-b border-ink-200 dark:border-ink-700 pb-2 mt-6 mb-4 font-sans" {...props} />,
                                    h2: ({ ...props }) => <h2 className="text-xl font-semibold text-ink-800 dark:text-ink-100 border-b border-ink-200 dark:border-ink-700 pb-1 mt-5 mb-3 font-sans" {...props} />,
                                    h3: ({ ...props }) => <h3 className="text-lg font-semibold text-ink-800 dark:text-ink-100 mt-4 mb-2 font-sans" {...props} />,
                                    h4: ({ ...props }) => <h4 className="text-base font-semibold text-ink-800 dark:text-ink-100 mt-3 mb-2 font-sans" {...props} />,
                                    h5: ({ ...props }) => <h5 className="text-sm font-semibold text-ink-800 dark:text-ink-100 mt-3 mb-2 font-sans" {...props} />,
                                    h6: ({ ...props }) => <h6 className="text-xs font-semibold text-ink-500 dark:text-ink-400 uppercase mt-3 mb-2 font-sans" {...props} />,
                                    p: ({ ...props }) => <p className="text-ink-700 dark:text-ink-300 my-3 leading-relaxed text-sm" {...props} />,
                                    ul: ({ ...props }) => <ul className="list-disc pl-6 my-3 space-y-1.5 text-ink-700 dark:text-ink-300 text-sm" {...props} />,
                                    ol: ({ ...props }) => <ol className="list-decimal pl-6 my-3 space-y-1.5 text-ink-700 dark:text-ink-300 text-sm" {...props} />,
                                    li: ({ ...props }) => <li className="text-ink-700 dark:text-ink-300" {...props} />,
                                    blockquote: ({ ...props }) => (
                                        <blockquote className="border-l-4 border-accent-500 pl-4 italic text-ink-600 dark:text-ink-400 my-4 bg-accent-50/40 dark:bg-accent-950/20 py-2 rounded-r" {...props} />
                                    ),
                                    hr: ({ ...props }) => <hr className="my-6 border-ink-200 dark:border-ink-700" {...props} />,
                                    strong: ({ ...props }) => <strong className="font-bold text-ink-900 dark:text-white" {...props} />,
                                    em: ({ ...props }) => <em className="italic" {...props} />,
                                    a: ({ ...props }) => <a className="text-accent-600 dark:text-accent-400 hover:text-accent-800 dark:hover:text-accent-300 underline transition" {...props} />,
                                    pre: ({ ...props }) => <pre className="bg-ink-900 dark:bg-black text-ink-100 rounded-lg p-4 my-4 overflow-x-auto text-xs leading-5 shadow-inner" {...props} />,
                                    code: ({ className, children, ...props }) => {
                                        const isBlock = /language-(\w+)/.test(className || "") || String(children).includes("\n");
                                        return isBlock ? (
                                            <code className={`${className} block font-mono text-ink-100`} {...props}>
                                                {children}
                                            </code>
                                        ) : (
                                            <code className="bg-ink-100 dark:bg-ink-700 text-accent-600 dark:text-accent-300 px-1.5 py-0.5 rounded text-xs font-mono font-semibold" {...props}>
                                                {children}
                                            </code>
                                        );
                                    },
                                    table: ({ ...props }) => (
                                        <div className="overflow-x-auto my-6 border border-ink-200 dark:border-ink-700 rounded-lg shadow-sm">
                                            <table className="min-w-full divide-y divide-ink-200 dark:divide-ink-700 bg-white dark:bg-ink-800" {...props} />
                                        </div>
                                    ),
                                    thead: ({ ...props }) => <thead className="bg-ink-50 dark:bg-ink-900" {...props} />,
                                    tbody: ({ ...props }) => <tbody className="divide-y divide-ink-200 dark:divide-ink-700" {...props} />,
                                    tr: ({ ...props }) => <tr className="hover:bg-ink-50/50 dark:hover:bg-ink-700/50 transition" {...props} />,
                                    th: ({ ...props }) => <th className="px-4 py-3 text-left text-xs font-semibold text-ink-600 dark:text-ink-300 uppercase tracking-wider border-b border-ink-200 dark:border-ink-700" {...props} />,
                                    td: ({ ...props }) => <td className="px-4 py-3 text-sm text-ink-700 dark:text-ink-300 border-b border-ink-100 dark:border-ink-800" {...props} />,
                                }}
                            >
                                {selectedSummary.summary}
                            </ReactMarkdown>
                        </div>

                    </div>

                </div>

                {/* Footer */}

                <div className="border-t border-ink-100 dark:border-ink-800 p-4 flex justify-end bg-ink-50/50 dark:bg-ink-800/50">

                    <button
                        onClick={() => setIsSummaryOpen(false)}
                        className="bg-ink-900 dark:bg-white hover:bg-ink-800 dark:hover:bg-ink-100 text-white dark:text-ink-900 font-bold text-xs px-5 py-2.5 rounded-xl border border-ink-800 dark:border-ink-200 shadow transition cursor-pointer"
                    >
                        Close
                    </button>

                </div>

            </div>

        </div>

    );
};

export default AISummary;

