// import React from "react";
// import useAi from "../hooks/useAI.js";

// const GenerationModal = () => {
//     const {
//         selectedGeneration,
//         isGenerationOpen,
//         setIsGenerationOpen,
//         generating,
//         handleGenerateDiagram,
//     } = useAi();

//     console.log("Selected Generation details:", selectedGeneration);

//     if (!isGenerationOpen || !selectedGeneration) {
//         return null;
//     }

//     const handleRegenerate = async () => {
//         const success = await handleGenerateDiagram(selectedGeneration.prompt);
//         if (success) {
//             setIsGenerationOpen(false);
//         }
//     };

//     return (
//         <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex justify-center items-center z-50 p-5 animate-in fade-in duration-200">
//             <div className="bg-white rounded-2xl shadow-2xl w-full max-w-5xl h-[85vh] flex flex-col border border-gray-150 overflow-hidden animate-in zoom-in-95 duration-200">
//                 {/* Header */}
//                 <div className="flex justify-between items-start border-b border-gray-100 p-6 bg-slate-50/50">
//                     <div>
//                         <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2">
//                             ✨ AI Generated Diagram
//                         </h2>
//                         <p className="text-xs text-gray-500 mt-1.5 leading-relaxed">
//                             Prompt: <span className="font-semibold text-gray-700 ml-1">"{selectedGeneration.prompt}"</span>
//                         </p>
//                         <p className="text-[10px] text-gray-400 mt-1">
//                             Generated by: <span className="font-semibold text-gray-600 mr-3">{selectedGeneration.createdBy?.fullname || selectedGeneration.createdBy?.username || "Unknown"}</span>
//                             Date: <span className="font-medium">{new Date(selectedGeneration.createdAt).toLocaleString()}</span>
//                         </p>
//                     </div>
//                     <button
//                         onClick={() => setIsGenerationOpen(false)}
//                         disabled={generating}
//                         className="text-gray-400 hover:text-gray-650 transition text-2xl font-bold p-1 cursor-pointer disabled:opacity-50"
//                     >
//                         &times;
//                     </button>
//                 </div>

//                 {/* Body */}
//                 <div className="flex-1 overflow-y-auto p-6">
//                     <div>
//                         <h3 className="text-sm font-bold text-gray-800 uppercase tracking-wider mb-3">
//                             📸 Generated Whiteboard Diagram
//                         </h3>
//                         <img
//                             src={selectedGeneration.imageUrl}
//                             alt="Generated Whiteboard Diagram"
//                             className="rounded-xl border border-gray-200 shadow-sm w-full bg-slate-50"
//                         />
//                     </div>
//                 </div>


//                 {/* Footer */}
//                 <div className="border-t border-gray-100 p-4 flex justify-between items-center bg-slate-50/50">
//                     <button
//                         onClick={handleRegenerate}
//                         disabled={generating}
//                         className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white px-5 py-2.5 rounded-xl font-bold text-xs transition cursor-pointer shadow-md shadow-indigo-600/10 hover:shadow-indigo-600/20"
//                     >
//                         {generating ? (
//                             <>
//                                 <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
//                                     <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
//                                     <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
//                                 </svg>
//                                 <span>Regenerating...</span>
//                             </>
//                         ) : (
//                             "Regenerate"
//                         )}
//                     </button>

//                     <button
//                         onClick={() => setIsGenerationOpen(false)}
//                         disabled={generating}
//                         className="bg-slate-900 hover:bg-slate-800 disabled:opacity-50 text-white px-5 py-2.5 rounded-xl font-bold text-xs border border-slate-800 shadow transition cursor-pointer"
//                     >
//                         Close
//                     </button>
//                 </div>
//             </div>
//         </div>
//     );
// };

// export default GenerationModal;


import React from "react";
import useAi from "../hooks/useAI.js";
import Loader from "../../../components/layout/Loader.jsx";

const GenerationModal = () => {
    const {
        selectedGeneration,
        isGenerationOpen,
        setIsGenerationOpen,
        generating,
        handleGenerateDiagram,
    } = useAi();

    console.log("Selected Generation details:", selectedGeneration);

    if (!isGenerationOpen || !selectedGeneration) {
        return null;
    }

    const handleRegenerate = async () => {
        const success = await handleGenerateDiagram(selectedGeneration.prompt);
        if (success) {
            setIsGenerationOpen(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex justify-center items-center z-50 p-5 animate-in fade-in duration-200">
            <div className="bg-white dark:bg-ink-900 rounded-2xl shadow-2xl w-full max-w-5xl h-[85vh] flex flex-col border border-ink-150 dark:border-ink-700 overflow-hidden animate-in zoom-in-95 duration-200">
                {/* Header */}
                <div className="flex justify-between items-start border-b border-ink-100 dark:border-ink-800 p-6 bg-ink-50/50 dark:bg-ink-800/50">
                    <div>
                        <h2 className="text-xl font-bold text-ink-900 dark:text-white flex items-center gap-2">
                            ✨ AI Generated Diagram
                        </h2>
                        <p className="text-xs text-ink-500 dark:text-ink-400 mt-1.5 leading-relaxed">
                            Prompt: <span className="font-semibold text-ink-700 dark:text-ink-200 ml-1">"{selectedGeneration.prompt}"</span>
                        </p>
                        <p className="text-[10px] text-ink-400 dark:text-ink-500 mt-1">
                            Generated by: <span className="font-semibold text-ink-600 dark:text-ink-300 mr-3">{selectedGeneration.createdBy?.fullname || selectedGeneration.createdBy?.username || "Unknown"}</span>
                            Date: <span className="font-medium">{new Date(selectedGeneration.createdAt).toLocaleString()}</span>
                        </p>
                    </div>
                    <button
                        onClick={() => setIsGenerationOpen(false)}
                        disabled={generating}
                        className="text-ink-400 dark:text-ink-500 hover:text-ink-650 dark:hover:text-ink-300 transition text-2xl font-bold p-1 cursor-pointer disabled:opacity-50"
                    >
                        &times;
                    </button>
                </div>

                {/* Body */}
                <div className="flex-1 overflow-y-auto p-6">
                    <div>
                        <h3 className="text-sm font-bold text-ink-800 dark:text-ink-100 uppercase tracking-wider mb-3">
                            📸 Generated Whiteboard Diagram
                        </h3>
                        <img
                            src={selectedGeneration.imageUrl}
                            alt="Generated Whiteboard Diagram"
                            className="rounded-xl border border-ink-200 dark:border-ink-700 shadow-sm w-full bg-ink-50 dark:bg-ink-800"
                        />
                    </div>
                </div>


                {/* Footer */}
                <div className="border-t border-ink-100 dark:border-ink-800 p-4 flex justify-between items-center bg-ink-50/50 dark:bg-ink-800/50">
                    <button
                        onClick={handleRegenerate}
                        disabled={generating}
                        className="flex items-center gap-2 bg-accent-600 hover:bg-accent-700 disabled:bg-accent-400 dark:disabled:bg-accent-800 text-white px-5 py-2.5 rounded-xl font-bold text-xs transition cursor-pointer shadow-md"
                    >
                        {generating ? (
                            <>
                                <Loader size={16} color="white" />
                                <span>Regenerating...</span>
                            </>
                        ) : (
                            "Regenerate"
                        )}
                    </button>

                    <button
                        onClick={() => setIsGenerationOpen(false)}
                        disabled={generating}
                        className="bg-ink-900 dark:bg-white hover:bg-ink-800 dark:hover:bg-ink-100 disabled:opacity-50 text-white dark:text-ink-900 px-5 py-2.5 rounded-xl font-bold text-xs border border-ink-800 dark:border-ink-200 shadow transition cursor-pointer"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};

export default GenerationModal;

